bump_version: null
lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-modulediscovery_logo_light.png
    - docs/images/nf-core-modulediscovery_logo_light.png
    - docs/images/nf-core-modulediscovery_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/igenomes.config
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-modulediscovery_logo_light.png
    - docs/images/nf-core-modulediscovery_logo_light.png
    - docs/images/nf-core-modulediscovery_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline
template:
  author: REPO4EU
  description: A pipeline for network-based disease module identification
  force: false
  is_nfcore: false
  name: modulediscovery
  org: REPO4EU
  outdir: .
  skip_features:
    - igenomes
  version: 1.0dev
update: null
