channels:
  - conda-forge
  - bioconda
  - nodefaults

dependencies:
  - nf-core>=2.10
  - nextflow>=23.10
  - prettier>=3.1
  - black>=23.10
  - pip
  - pip:
      - spython # This is the pip package equivalent for singularity-cli

# Note: The 'singularity>=3.8' line has been removed as it is not available via Conda channels.

